language: cpp

compiler:
  - gcc

before_install:
  - export CODECOV_TOKEN="722eadc3-4255-4beb-9a77-e967a211530f"
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository ppa:snaipewastaken/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install criterion
  - sudo apt-get install -qq g++-8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script:
  - ./tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)