language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:snaipewastaken/ppa -y
  - sudo apt-get update

install:
  - sudo apt-get install g++
  - sudo apt-get install criterion

script:
  - ./tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)