language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:snaipewastaken/ppa
  - sudo apt-get update

install:
  - sudo apt-get install g++
  - sudo apt-get install criterion

script:
  - ./tests.sh

after_success:
  - export CODECOV_TOKEN="722eadc3-4255-4beb-9a77-e967a211530f"
  - bash <(curl -s https://codecov.io/bash)